### ISSUE TITLE
Does not start if path contains a space

### ISSUE THREAD

**Issue by gabrielstuff** [mfuhrmeister/nodejs-embedded-mongodb-standalone#4]
See https://github.com/nodejs/node/issues/6803 the issue is related to how node handle this type of filepath

Thanks !

**Comment by marcusfuhrmeister** [comment]
Was away quiet a long time. I will fix this as soon as i can.

**Comment by gabrielstuff** [comment]
Thanks ! Great to see you are working on it.

**Comment by mfuhrmeister** [comment]
Resolved in v1.4.0
