### ISSUE TITLE
add support for --dbpath

### ISSUE THREAD

**Issue by gabrielstuff** [mfuhrmeister/nodejs-embedded-mongodb-standalone#5]
Would be nice to be able to specify the dbpath when starting the mongo instance.

**Comment by marcusfuhrmeister** [comment]
Will look into it, thanks for the advice.

**Comment by mfuhrmeister** [comment]
Working on it. Thanks for the advice.

**Comment by gabrielstuff** [comment]
Wow great :) wasn't expecting it ! Thanks.

**Comment by mfuhrmeister** [comment]
Feature added in v1.4.0.
